data_ingestion:
 bucket_name: "tap30"
 object_name: "data.txt"
 storage_location: "https://tap30.s3.eu-north-1.amazonaws.com"
 train_ratio: 0.9
 artifact_dir: "artifact"
data_processing:
  shift: 18
model_training:
  n_estimators: 500
  max_sample: 0.6
  n_jobs: -1
 